config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  root to: "recipes#index"

end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
	has_many :recipes
end

app/models/food_preference.rb
class FoodPreference < ActiveRecord::Base
	has_many :recipes
end

app/models/food_type.rb
class FoodType < ActiveRecord::Base
	has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	DIFFICULTY=%w(Easy Medium Hard)

	belongs_to :food_type
	belongs_to :food_preference
	belongs_to :cuisine
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :sidebar_values

  def sidebar_values
  	@food_types = FoodType.all
  	@food_preferences = FoodPreference.all
  	@cuisines = Cuisine.all 
  end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :cooking_time, :dificulty_level, :food_type_id, :food_preference_id, :cuisine_id, :ingredients, :procedure)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Curry Nation"
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags

  %body
    %nav.top-bar
      %ul.title-area
        %li.name
          %h1= link_to "Curry Nation",root_path
      %section.top-bar-section  
        %ul.left
          %li=link_to "Recipes", recipes_path
        %ul.right             
          - if user_signed_in?
            %li= link_to "#{current_user.email}"
            %li= link_to "Logout", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Login", new_user_session_path
            %li= link_to "SignUp", new_user_registration_path
.row        
  .small-4.medium-3.large-2.columns
    .side-nav-section
      %ul.side-nav
        - @food_types.each do |ft|
          %li= link_to "#{ft.name}", recipes_path(sort_by: {food_type_id: ft.id}) 
      %ul.side-nav
        - @food_preferences.each do |fp|
          %li= link_to "#{fp.name}", recipes_path(sort_by: {food_preference_id: fp.id})
      %ul.side-nav    
        - @cuisines.each do |c|
          %li= link_to "#{c.name}", recipes_path(sort_by: {cuisine_id: c.id})    
  .small-8.medium-9.large-10.columns
    #{yield}

    #{javascript_include_tag 'application', 'data-turbolinks-track' => true }
    #{javascript_include_tag 'application'}

app/views/recipes/_form.html.haml
= form_for(@recipe) do |f|
  - if @recipe.errors.any?
    #error_explanation
      %h2
        = pluralize(@recipe.errors.count, "error")
        prohibited this recipe from being saved:
      %ul
        - @recipe.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :cooking_time
    %br/
    = f.text_field :cooking_time
  .field
    = f.label :dificulty_level
    %br/
    = f.select :dificulty_level, Recipe::DIFFICULTY, {} , :class => "form-control"
  .field
    = f.label :food_type_id
    %br/
    = f.select(:food_type_id, options_from_collection_for_select(FoodType.all, :id, :name), {:prompt => "Plase Choose"}, :class => "form-control")
  .field
    = f.label :food_preference_id
    %br/
    = f.select(:food_preference_id, options_from_collection_for_select(FoodPreference.all, :id, :name), {:prompt => 'Please Choose'}, :class => "form-control")
  .field
    = f.label :cuisine_id
    %br/
    = f.select(:cuisine_id, options_from_collection_for_select(Cuisine.all, :id, :name), {:prompt => "Please Choose"}, :class => "form-control")
  .field
    = f.label :ingredients
    %br/
    = f.text_area :ingredients
  .field
    = f.label :procedure
    %br/
    = f.text_area :procedure
  .actions
    = f.submit

app/views/recipes/edit.html.haml
%h1 Editing recipe
= render 'form'
= link_to 'Show', @recipe
|
\#{link_to 'Back', recipes_path}

app/views/recipes/index.html.haml
%h1 Listing recipes
- @recipes.each do |recipe|
  %ul
    %li= recipe.title
    %li= recipe.cooking_time
    %li= recipe.dificulty_level
    %li= recipe.food_type.name
    %li= recipe.food_preference.name
    %li= recipe.cuisine.name
    %li= recipe.ingredients
    %li= recipe.procedure
    %li= link_to 'Show', recipe
    - if user_signed_in?
      .button= link_to 'Edit', edit_recipe_path(recipe)
      .button= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' }  
%br/

%a= link_to 'New Recipe', new_recipe_path, {:class => "button"}

app/views/recipes/new.html.haml
%h1 New recipe
= render 'form'
= link_to 'Back', recipes_path

app/views/recipes/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @recipe.title
%p
  %strong Cooking time:
  = @recipe.cooking_time
%p
  %strong Dificulty level:
  = @recipe.dificulty_level
%p
  %strong Food type:
  = @recipe.food_type_id
%p
  %strong Food preference:
  = @recipe.food_preference_id
%p
  %strong Cuisine:
  = @recipe.cuisine_id
%p
  %strong Ingredients:
  = @recipe.ingredients
%p
  %strong Procedure:
  = @recipe.procedure
= link_to 'Edit', edit_recipe_path(@recipe)
|
\#{link_to 'Back', recipes_path}

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>